# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'EfullWalletNative' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for EfullWalletNative

  target 'EfullWalletNative-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'EfullWalletNativeTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'EfullWalletNative-tvOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for EfullWalletNative-tvOS

  target 'EfullWalletNative-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
